[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<test_fire.cpp>

[env:test_fire]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<main.cpp> +<test_fire.cpp>

[env:timer]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<main.cpp> +<timer.cpp>

[env:test_cycle]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<main.cpp> +<test_cycle.cpp>
